# Generated by Django 2.2.7 on 2019-11-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_logo',
        ),
    ]
