# Generated by Django 2.2.7 on 2019-11-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_logo',
            field=models.ImageField(default='../../assets/images/default.png', max_length=500, upload_to='media/'),
        ),
    ]
