# Generated by Django 2.2.7 on 2019-11-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_artist_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_logo',
            field=models.ImageField(default='../../assets/images/default.png', max_length=500, upload_to='media'),
        ),
    ]
