# Generated by Django 2.2.7 on 2019-11-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191123_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_logo',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
