# Generated by Django 2.2.7 on 2019-11-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191123_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_logo',
            field=models.ImageField(default='../../assets/images/default.png', max_length=500, upload_to='E:\\Mugen\\media'),
        ),
    ]
