# Generated by Django 2.2.7 on 2019-11-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20191124_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(default='default_album.jpg', max_length=500, upload_to=''),
        ),
    ]
