# Generated by Django 2.2.7 on 2020-08-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
